{% set name = "xopt" %}
{% set version = "3.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 233b31faeeef4c9caea6d8eae388dff9487f578fecbd257031f7ae4b451ba490

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy>=2.3
    - pyyaml
    - deap
    - pytorch
    - botorch >=0.17.0
    - gpytorch
    - pandas
    - pydantic >=2.12
    - orjson
    - matplotlib-base
    - gest-api

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
    - openssh
    - python {{ python_min }}
  source_files:
    - xopt/tests
  commands:
    - pytest xopt/tests

about:
  home: https://github.com/xopt-org/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
