{% set name = "xopt" %}
{% set version = "3.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1c9cec1defe479a4460db870a9d87c922f35d766083aab294252b37e7e9ed06

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy >=2.3
    - pyyaml
    - deap
    - pytorch
    - botorch >=0.17.0
    - gpytorch
    - pandas
    - pydantic >=2.12
    - orjson
    - matplotlib-base
    - gest-api
    - scipy >=1.10.1

test:
  imports:
    - xopt
  requires:
    - {{ compiler('cxx') }}
    - pytest
    - mpi4py
    - dask
    - openssh
    - libensemble
  commands:
    - pytest --pyargs xopt.tests -v

about:
  home: https://github.com/xopt-org/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
    - Roussel-Ryan
    - pluflou
